### PR TITLE
initial version

### LINKED ISSUE #1: initial version

### PR DESCRIPTION
**Pull request by odinuv**
fixes #1 

it just reads the config file

### CODE REVIEW

**Comment by odinuv** [comment]
whoever comes first :)

**Comment by pivnicek** [comment]
checking it out now.

**Comment by odinuv** [comment]
yes - it has the wrong template https://github.com/keboola/data-loader/issues/37

you need to create a new notebook manually
image

**Comment by pivnicek** [comment]
aha!  ok, closer, but got 
image

**Comment by odinuv** [comment]
`master` -> `odin-init`

**Comment by pivnicek** [comment]
alright, I got
`SystemError: opening file "/data/config.json": No such file or directory`
But I think that's alright, since there is no datadir so it should say that

**Comment by odinuv** [comment]
yeah, there is no config file in sandbox, so that's more or less correct :)

**Pull request merged**
